# Generated by Django 5.2.10 on 2026-02-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAddictionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('da1', models.IntegerField()),
                ('da2', models.IntegerField()),
                ('da3', models.IntegerField()),
                ('da4', models.IntegerField()),
                ('da5', models.IntegerField()),
                ('da6', models.IntegerField()),
                ('da7', models.IntegerField()),
                ('da8', models.IntegerField()),
                ('primary_device', models.CharField(max_length=20)),
                ('own_smartphone', models.CharField(max_length=5)),
                ('mobile_data', models.CharField(max_length=20)),
                ('screen_weekdays', models.CharField(max_length=10)),
                ('screen_weekends', models.CharField(max_length=10)),
                ('night_phone_use', models.CharField(max_length=10)),
                ('notif_per_hour', models.CharField(max_length=20)),
                ('social_time', models.CharField(max_length=10)),
                ('gaming_time', models.CharField(max_length=10)),
                ('platforms', models.JSONField()),
                ('self_rated_da', models.CharField(max_length=20)),
                ('predicted_risk', models.CharField(blank=True, choices=[('Not at Risk', 'Not at Risk'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
